In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.min()

np.int64(1)

In [5]:
arr.max()

np.int64(9)

In [6]:
arr.sum()

np.int64(45)

In [7]:
#column sum
np.sum(arr,axis=0)

array([12, 15, 18])

In [8]:
#row sum
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [9]:
arr.mean()

np.float64(5.0)

In [10]:
#standard deviation
arr.std()

np.float64(2.581988897471611)

In [11]:
#argument of max(index of maximum element)
arr.argmax()

np.int64(8)

In [12]:
#argument of min(index of minimum element)
arr.argmin()

np.int64(0)