In [4]:
import numpy as np

In [5]:
#create array
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
#create list
a=[1,2,3,2.3,"hello"]
a

[1, 2, 3, 2.3, 'hello']

In [ ]:
#convert list to array
np.array(a)

array(['1', '2', '3', '2.3', 'hello'], dtype='<U32')

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#create array using range 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#Give me a linear space between number
arr=np.linspace(0,2,num=6,retstep=True)
arr

(array([0. , 0.4, 0.8, 1.2, 1.6, 2. ]), np.float64(0.4))

In [18]:
arr1=np.linspace(7,9,num=7,endpoint=True)
arr1

array([7.        , 7.33333333, 7.66666667, 8.        , 8.33333333,
       8.66666667, 9.        ])

In [19]:
arr2=np.linspace(7,10,num=4,endpoint=False)
arr2

array([7.  , 7.75, 8.5 , 9.25])