In [1]:
import numpy as np

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [5]:
arr1=arr[bool_index]
arr1

array([12, 14, 16, 18, 20])