In [1]:
import numpy as np

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[9]

np.int64(20)

In [ ]:
#slicing arr[start:stop:step] strat->inclusive and stop->exclusive
arr[1:5]

array([12, 13, 14, 15])

In [5]:
arr[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [6]:
arr[3:9:2]

array([14, 16, 18])