In [1]:
import numpy as np

In [ ]:
#normalisation
np.random.rand(10)

array([0.3196919 , 0.04494555, 0.88607868, 0.43247896, 0.22010285,
       0.26348262, 0.5347536 , 0.92881522, 0.79078181, 0.82095803])

In [3]:
#standerdization
np.random.randn(10)

array([-0.70550738,  1.85217235, -0.49561402, -1.57137021, -2.16937978,
       -0.33352097, -0.16304104, -0.82950725, -0.27297846, -1.26415484])

In [4]:
#generate any random number
np.random.randint(10,20,10) 

array([13, 15, 19, 12, 10, 13, 13, 11, 19, 10], dtype=int32)

In [9]:
#generate any 1 number between 0 t0 5
np.random.randint(5)

3