In [1]:
import numpy as np

In [3]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#print rows(0->n-1) n=number of rows
arr[4]

array([21, 22, 23, 24, 25])

In [6]:
arr[0]

array([1, 2, 3, 4, 5])

In [7]:
#print element
arr[0,4]

np.int64(5)

In [8]:
arr[4,3]

np.int64(24)

In [12]:
#slicing matrix --> matrix[start(row):stop(row),start(column):stop(column)]
#where start is inclusive and stop is exclusive
slice1=arr[0:2,1:3]
slice1

array([[2, 3],
       [7, 8]])

In [13]:
slice2=arr[2:5,0:4]
slice2

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [16]:
slice3=arr[3:,3:]
slice3

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
slice4=arr[:,2]
slice4

array([ 3,  8, 13, 18, 23, 28])