In [1]:
import numpy as np

In [5]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])

In [ ]:
#Stacking Array-->use vector not matrix
vertical=np.vstack((A,B))
horizontal=np.hstack((A,B))

In [8]:
vertical

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])