In [1]:
import numpy as np

In [3]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])

In [4]:
mat1

array([[1, 2],
       [3, 4]])

In [5]:
mat2

array([[5, 6],
       [7, 8]])

In [ ]:
#Wrong multipication of matrix
mat1*mat2

array([[ 5, 12],
       [21, 32]])

In [7]:
#Right multiplication of matrix
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [ ]:
#we can also use for multiplication of matrix
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [9]:
#for Transpose of matrix
mat1.T

array([[1, 3],
       [2, 4]])